remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

logo: https://disesdi.github.io/spider-f.png

title: Angles Of Attack

description: MLSecOps for industry, aerospace & defense
